# Generated by Django 5.1.1 on 2025-07-31 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Kategori Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ürün Adı")),
                (
                    "material_type",
                    models.CharField(max_length=100, verbose_name="Malzeme Türü"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("E", "Erkek"), ("K", "Kadın"), ("U", "Unisex")],
                        max_length=1,
                        verbose_name="Cinsiyet",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(verbose_name="Stok Miktarı"),
                ),
                (
                    "size_info",
                    models.CharField(max_length=50, verbose_name="Beden Bilgisi"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Fiyat"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Resim",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün",
                "verbose_name_plural": "Ürünler",
            },
        ),
    ]
