# Generated by Django 5.1.1 on 2025-08-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_id_alter_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Açıklama"),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste formatında: ['etiket1', 'etiket2']",
                verbose_name="Etiketler",
            ),
        ),
    ]
